---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-root
  namespace: minio
spec:
  encryptedData:
    password: AgCYm8PRBGzRNNHDHTg0ip9BOacYu6rwDxtF5EcAFbtserjg+Oc0lH5kzpF3E2fViIiVcroURWpFfNruGKL8QjvBpiRPZCqHxkMKvfld1+GLCnHMwGo5AquR44B0DUa1FxbQlfYEpJ+PVkDE7JdUH2ygaecRva02yKCoIoZS1EMId9aKAg5g80N0GhftdIxNqd463fVzR1O5xIXODkQGgC2HTozLUVqyxhXAIcJkyFzFfb0tNfNjTIrST1+e/IyAl5JJ5B/J075Q4Qd3GIHiode0/mDaaTOhhgSapODdqUB6mutNFQt6HWGUmy2Qns8agcl2s6LgqABdSNGYY5weMzZRVWSYZPscmcqZSoi45yRcQU9/n3iIQEP9UTFKMlvfj+k7pmH2xfIXnBne5vQJG+856O8wSPnaElSP4MNmtJmmz831sswE2N2dqmA1TKt7Hf6RymDM3wB7t8muR0VbMtCcfHHAQKgZar/FI2xE36Etp8jn9oiat5vw4TNIswq2K+KyG3weVHY81RnQ9HtU/Bwx3EfoGr6UYdkAVeu5XROZQtPzfwT1T4JL383xfXuz3l0hNvLG1F8l0Wu7tBFRS3qwy4nVGRynNsi3e/m5Ww9tcX8M/n9YqKuVZzYqeJ9mDsCAm+eB0O9baEZY7Eep6OIJq1MXYs0fTmf1nw8i/ej4ftnRSzpnf1b1835vnFJNwJErd/P3dYnYOQP+chZaVqXahI6FXuF0cJFStfKDzF5ZpQ==
    user: AgCwP7t+hQi+phD8xLFYjHAXJgbWu+3oyQJV3xpkylAhDbAHSH9l2QW/4oOMWZN3VC1h93apBETWqLT5mqisTu+zQysDroJ7wWRA0uGYpMhaDCZaGc/cmDY2jvwdcLmw1qhGAvhfdk6hwdKrBVJBdkkSk96NgsA7pSg+jRv1XUdTs2f77XjZg0GCUDSXuo3ate89ATecG/PVTzub9l261OfkUtSc2Hx607fBhAfcgc6VJiuVv6r+tFrudpbAK/H3KsVOQGz8YEqc20A0BfL4G5C/BBL/GUjnghyiG3636C1vLgxSahQwMKBv1GWua+vCjA3obQXCAYWEfUDlDkl6YuI2XF7fCmh9BMuEU8Iyj7rYlGnHFhwqmWXNFivRL6Q5pOTyPR6uNl8IazZCDAEVC23xTXD9A0wzjH1qTJk9jzG1zLH8kjIDg9liYrpUSuOGQULn2ylMP7RXOxnwjIRLMuqoxFE2aJhI/xBRJikv2EsO38FylkjOVFHH39+f7Ijs1odi9JQ3oDQyel7QrEHWgfIXDd2nwXetet+KjOY6D0VPwnorrsgxxREq0dqH2H9vZLLtHNK8pEm7WYYs/Cnm1XvFxpeasn75Bm8/qaL20KxDOHZAVSHgclTX/mCw046ogFscx5sr7IK0EpBdhS/zmyRGg/YuvIi6orUYywh/6y/9mohoDultdDke7o0N0lDHoxFlFt11SFaD5c2xvprc14127g==
  template:
    metadata:
      name: minio-root
      namespace: minio
