[package]
name = "skycam"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "skycam"
path = "src/main.rs"

[dependencies]
rocket.workspace = true
mongodb.workspace = true
bson.workspace = true
aws-sdk-s3.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
futures.workspace = true
domain.workspace = true
