[package]
name = "release-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "release-proxy"
path = "src/main.rs"

[dependencies]
rocket.workspace = true
mongodb.workspace = true
bson.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
reqwest.workspace = true
futures.workspace = true
jsonwebtoken.workspace = true
bytes.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-credential-types.workspace = true
aws-smithy-types.workspace = true
domain.workspace = true
