---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: observatory-release
spec:
  encryptedData:
    mongodb_uri: AgAoY02ZhJ5Ef8N/pvcCp60c+K7l8xrCmYMjbl2RRh8GyAidgG/+mO/+MtH4CUwYNeckz0P0Lv1+bAjPxQLtY901VNtmizkm8HGMXP7TW8bjuiWrRVG/o+PhGoN/higFhtl5AI5jsM5OCX9h/dhuVrOygV/yWf/nSgHG6BNkmwLx6pFOCrQC772GrHniC1wZhfpecd5rQBVZODxUDvkDL1AUDnvtQGMBVbRviHfsMJGADJoMbKHCI0e8VE8yG5fmRKVVVMrV2t65ctaId8vdJOPuiAi3wreNff/NEFWduSm+dbCTDcsL4tMusowhIphHmASMVtrVNUTICfMHOb+UsZHO3+rEjilldHegCgX/IlTJzxdDfYPQ4L1G8Hpy+zp26cWH4wndR4CABBSRlCciJl7MOzSnzi9UfwcdY1FDH6NJh8F8/5wKwxZup4hvy0jZM9+jJ+0QCDOSjk4pdJ0CcmKDtKYw+H+6ajyu1p9SQqPTpsPoOc2R3p+eapPWzjQRO/lbW6YSeRbGpXO53jO5AFiqsvpA2+IyOpW5p4eJFB7/9/NaRBEpTD01SDNw0/Zm6I14EglmfyjuDESGk7QcIpiAXwykaXoqqNbU+D5OLUWhJ00pSMBDxdjDynu9tM6SaKrQTK9CEm0ULO80rbQwJMviRFOXdZll+3gi/YOJTvRlZrGUTG179CAX/fwGv8wERz32r1UHq2Y0ZZ739zH5/HdRsxxMdk2WAPChAuzD9LYP4sJQXZDYvR1Q6MUYkmAiHAa78pfM8V2gpRpAYGwqtnRn5nNlo/ILh8wgWL7Itg2if96o+0wTgNCCnHiGxbkAGNPUTEG45EOx1Wc=
  template:
    metadata:
      name: api-secrets
      namespace: observatory-release
