apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatory-release

resources:
  - ../../base
  - mongodb-credentials.sealed.yaml
  - api-secrets.sealed.yaml
  - release-proxy-secrets.sealed.yaml

configMapGenerator:
  - name: app-config
    literals:
      - environment=release
      - mongodb_db=observatory_release
      - s3_endpoint=http://minio.minio.svc.cluster.local:9000
      - s3_public_endpoint=https://s3.observatory.services
      - s3_bucket=observatory-release
      - s3_region=us-east-1

patches:
  - target:
      kind: Ingress
      name: observatory
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: release.observatory.services

images:
  - name: ghcr.io/observatoryservices/observatory-services-api
    newTag: release
  - name: ghcr.io/observatoryservices/observatory-services-release-proxy
    newTag: release
  - name: ghcr.io/observatoryservices/observatory-services-frontend
    newTag: release
