---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: observatory-release
spec:
  encryptedData:
    password: AgBWqBV328+Bky9OGZ3ZvuWGjMFbhqLpA4kUL0yddvtJFPMYygL5hZmjaOUnlph5xA6M8hFn0x1rOciwxRbeQyI5PByTiM8Rz7FlZxk7SuxzbIiRSDYTCRNwKkj8uOJIocZgUkU8jldfdcjvoRXQvvNoYUCV2DcS9lEXJJDni9wRhj2kStRz9ZzMjuyfbwbZuyrrCGU6ULndhurhoXN2Efn3PhTLyodoGYqyVK+ijAPpORvMgaw9JBoeZJwqX9m92nWI56UICN1LjN7kvvZFMXFTrr+AtG8DS//wMZHRl5MZoOIwKZnnHglWqkPZoz4GCs4kHYjMPKoAgGFCa94H17KCtXTAcLHKYKUBakdYiIWArplHPQLyEfq0Y1Ps8GSPmmbzoGsRnf8BHw5SDNz5f2hrR2srH/c+cYWnt9gi/C86BIjhHS2STV+wQsqxH/B8ZaBOf1LSM8Fk7MEI6OLgARShH2QofguXWJIYrAF6ym8bz6y9bu23kIRA/Z2Gf/ksEASdMsOso8fB39PjfM04HKtiuNTJsLj4VwI8vQ+/j5AcZYMFBw/+tzwtTDiXhgwFA81Qcx0bGxiNj3ty7qw/4oGnU3z1kYyTXNIGz7qP0DNj3ltYe8nJhiME5UzRE4w7ZHV+iZZ7rRjJ5/el+JpQmdK9ac0mnNp/m5Ue1XRgWIcfYDiKXN4xGHuQwaZGR18MCR8k35DEKAsG4G4cKqkLgJvtcOGvtNR89swgtp3qZZbLQw==
    username: AgBduJiRX9K2wS5TXDZCiTjTXe+EJz5VrvBufAi8cKZjWoiALzOsFRvAizA4UgYUmJG7j6qpyFplCJOh0watBZ4RUjSBfrw9HiKLPMpRGdEJX3dnHZh54qLKSI0vKwALiom2FWu7AJhB6vwpHwljgNYmgggvJTNqwrB/lG7a/1OcEvpZm4YBNbnY7uVFi6vbouda7SfaP2UiqsCsOBwsMAxjR/TXGy36+4L++rUHfgjXF+iJxKT7sQyWtXAp891sMK1dLVRh6lh5WalvxiRtN60onh9BThi67Qz18XK0aViB3Ptjq94Q4zjsNuA4fdyY+LMRxkVSUTbT59KWIJ0+hIRe093F2OSzMYRMnjqjJhZrS3u6Alg7A6c2Gcda/8RPm5VUC738+ObvSuCzwaRLhcgt8e685Hfu99TcupaISu7lz2DQZLxYuA1Ww6sIGkKy6k8YwBmr6PsHL7pYYKX+X5AwJOnLc6PwidHk4hpKIUCEfZQac1piV2aZ+PghR5wc10yPFdIlj9pTwjEgAabGbqPHu0U9XJkw6KGOerjVlpk050J6Eh6JYioq+WV9J5e6btmmVF9R0RtrwJ8rGxtqLRJgNcYHYnmfsgDB36NiXA6JZnf2NhvAriPr9ZjdRqHh0CclAELCnkNYY1tOrhzjiYQvjrNPU/WSfsqUY5XjAsrrPQAPeWETXMciSfOFHsvwJFrLypMs5vQJQ1hkBw==
  template:
    metadata:
      name: mongodb-credentials
      namespace: observatory-release
