---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: release-proxy-secrets
  namespace: observatory-release
spec:
  encryptedData:
    s3_access_key: AgA1YZqczlbm1i0svUNZBfJ570tKii5llSQfpp7zx1RWGT6N/p1+1Huy6Wh8Kyqs1ZRidkfRmV7f3s/3sh1/6tkandW0cTk+1Ebh4S8Feu9xKzoQK9DfjIN47ggeqdYcssLkIa4VPH8nH7XMqSzBAyv+wKMBNyIKKYKNN2aoRBKeF0UYSwvJqsPF7Hu90Dqi8USAto7H5D+HSKv5d/nVi8U3Iv9cn8Rw9Jad/5a0u7BHYGGUP4t4zVlFzf4Obd1mxhf9GB75KgL/sf5MeqDOjNUCwHpGr6f9ahtMtVP88FxX+DnDI2IqV/CCOOighF0n8JIv5+6ipTVgm1pAQsvEJgIiPvhEm8MgtR4uB4P1IUK8gdb3BY/5kegEvYyViqUc4gGZdwugdcVZc6GyYzM5d+xUlDVFgM78fikP4iNfVP7Yaw8k6A8Exzlbe5SikgJZFVfaUn4gia6EMerHFauedUOi5f752VoYJKNYPaYsaj27WrF3xuukUV4lOwh7QVSR2WHpB/EQ5oneV/ujTvCn2/sYtcLT//sO/QIKxwDW8J8GYY3dWdDmhY8lb7SNzNFNS6yF9j+yjFjU5ph7MOLCZm9y3+keIFqgFZTD2PiUmGYNPm9sNfmNJbQrXdOdYIKUhtHngn6GnamvrecbiXMP9L8Xmdppo7csfsqK115grpNycArgvXSsVfagMEiA2m3idACBLsBe/YtZrmr5n7ABSwqAaGK2VQ==
    s3_secret_key: AgBronE6ANf093/E1/inAF9cSXbsiHYm68+JaxxBAZZjOmSXlPILBa8YhgE4F3q/6+7waCnoFhoS6g2kHBbIQ90X1G5RHu7lQkNmMQ7D/wWEh/0Uc8BurotVvv+FDqp68+Fkwn3/qT0QLm+CPSNer0jBFOWBCyuBCOHSUEnYPNKJQ6vXWGhyNVmzk+vXkfXVxEzHnHPYJqyINzRrj9dixyHDGGZuSL6xPMYgYQyzC4CI9OuQ4EUNJ9yhd9nDLByfFD8j0RyCM8t8qzIMuQWvuCji3uk0OXb8bTp4tmorjcGAaisGfnDc6pDktsI2/qoeH/Mf6JoE5RD4pAESBjNv2jthrnzj4ItRTn2kmSHbEinNPyur67P0CBgaxdsgvOUUhOBVinTHKhMepYL8nXZDi9j0EOWifxpxGruWuRse1HuzLS//tc3xj4/tSR9QKd4AvrwlapIuZI1YPFvRlteRwKgS356GI57F4uGjaI84KaZfqAx/ScQvvNK9LnBLbS1rzkzVrz2clqz4HoEa5Te8gNS/hMidHULn4NvwvDrLOdMHvhBcbPTmW5/gPAsC28lSyHanbR2XXJpwKzljswSuFFSgIqzCZVVcV8BxoBQQY+jAxxb0LmSnumzvGlKXWg1Bb2RgYu35npWs/Tx9jDIw4nq6WlGE5Yc/2mihtMu8cL+uqhfMWefrAkX/19MJUc+nlfXqGQ3ryzvtDzoodsGEBJH2kbDUYSvfmY8gfKJIwyjnXLvWRV4W0Rpd
  template:
    metadata:
      name: release-proxy-secrets
      namespace: observatory-release
