---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: observatory-dev
spec:
  encryptedData:
    mongodb_uri: AgCTu8tQ6bMGGfqhaiYQMLSFXP58QuIKAqG4lebW8DCGkh2IPX4WenRYHILeX3VSIfPCW3ftbv3PamkawyShbOhAdVOXVzMlVKaaQhI1BU309L0nt4d2W7MI7T70VbFIc4YRARvaAwqgiGdXhwWaIz6Szhuo3eoOIdM9ikIfea9cdapO9L+Wu3aSQ/bdhI+J4RyZJ0lnwFLnPdptERRRJNUFiiM57IDkfekM9GHM3Ujxg8ibwYCHvwDSzHcwaHqNqE4IH3L0/mO7YTApZZObRqBzXj9Ir/2iH2NFLNrEk4FnNsy9vl18aidx1HUqrCY4IA8IIL3pwqkZN8DRQRRhoTO1VS8A1SgtqX0qetGUpYD23rXmybM2hhcfhKpBSmgPW/NUWLqFDzkfNYrU1JKcCuMYg98Ugxlvr8uNv269o68IemhS0tSuPjXCTKiAZ2adIeoteXJa0Atfr0SAy4T6byydAhZ9peiNEWFtNktMgUTysEQjhndcey43c3Y5RJGam1WPhnunRAyIFqQoXI/Hszu18XH5lP1J8qzkbhreJGbacuCZJN0vHdm31xatdKXZFi6sc1gxlZelDasTvow48vmND4WDSLTijt91hSSdgdyXJqTm/E1h808z036psYIzXlnYFmwim1mB8lerKObYV1/b+nqebjbcgTKxLOoHXWXMcBd4W4HjKBHcJFlr/Ie3XHhdJ2f2gLXli6jE8FVLGHMIxH9Py/B8hdbsX2b6d7YvjaaCtE9SPr4IV7dhONNo4lHpDW28EjrPMXSW26SQ5FrfFC82PE1cpQUjssOaFeWehdAPj/mI41ZL84MpqhYqgIT0tVZvXg==
  template:
    metadata:
      name: api-secrets
      namespace: observatory-dev
