---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: observatory-dev
spec:
  encryptedData:
    password: AgAZg87HupO11OwgFs8KMGMdD7CTHQ2NCMJ2LBkfNSuraB8ssmshFB7Ns0oin/NRbbxILP5YYEvDJVbC95laLr4Zlli0/0WB5ncG+3jlnj3juBGVY4V+VgvLeqgk5CY41ruAuVUrxgXAih/NEUf5poLJBxs2tG4mU6Kmu2E3/w2+9RLNXGPwJzyUa3l545LpVW2ymWxl9eY6udOREzUW6XIzFo0hAC78jQ3i1+tUExjMXBFYOqha0H+Mg+OQFCUldOANNfNNrW2U8VCbR56KJhyOqMbzQBExnnyqcQ6iCvkmEMjld85nqEjdrZOecXAfFBeowGyFMWcvISrgy85317CDf/Gfx7nUeLgRQQNCMpZCJe08v47xzcoAAwWHx/Dy4yeWSWbqJbVIZMtNoBi/Vo1KncoyLTKnJ9n7jlMK32GrusdWmAjJWnIIMqqCD0/kGpzHHOHdeO5ahx3iSDLJkc1wiV2hSwRb65wk64L/E2HuSUPOwbNZ8ZtgTaExv/QbMaVO8wH+AudaiQNbqQ7DeumiZy+lf90UerImCP+7NmK5hDu620XHpe5c71eEBx6AqO9dr8oEeWD5vQTONjh6Xy1mq2AyijEANnwmYfIjCQ4qKYzNUucrQrqnqwx9wS2gy+9UQt+jJTs8ndGb7culHPYOduCB5U2vw7dBueHT5gxF6QtKK1d5ejidab/ORupWI1dsUzXRBSVlF6ZqxItRTp4bDt4koEWLfRcagGhayHMbtQ==
    username: AgBu6agLRnOtE5sD4sQidITvPZ1gL66h0uPRo5BVfheS3ajcwLp/zRPLT/g6H3qAyJmyQmIgb72K/MzNlY6Ujns7W9dsigEPVz28Uq/gngB8XuKq8UDrXucLTaWhPuhoTcd/2cvE7z8LeYkr7fGjtuJEWDsoRR5elzFVlqvjB6HEWtEIZZSX4nRPMptdbS3R2B1cDcJowrqeqXoT2woBK+b7Go1AomObbNAWco98dPd9dJ7jppJF1mkpFrSPaIWzlGGDIRzuBBxUMPyQJYOf88aetieQ49NC8Tvi+rHa8y84Sbcs9HUN0Q7/nAJXCrlT4eGbcWJLjCYRuF/Lgo79/OrKb3B8j5auWgI/Qm1uGjkO9Fhzd1qfWXfy5Ghc8EiIQ4KahHgSOWzLCFrZtsWN/CnDaG93k0FuzRpmmivwE3G2fArfE6vINRywHBou5UhWUijyJgC3cdrVUNIxOdvj/7XgCXUMWkFbASTx/mygz3w28So0Ar6Rwu6zd5j3DfSZRIdbxX5OV8BWB0vwTmpNE24WGI8A3vm0kX1k2hPvpgkrDO4pLj7AfYiwr8t360l6hIGAKEfaZrwov0/ej0eybkqI4H0/BBK/3EbZg200ZhH1sHci1q35oIfaTZLfiqs/1a+TPEoeBOpawF9lXVdvaetbIHx3vwTlO+JEdmc2JG9Ih2OZNGpvhbvsrjVFfsQK1O3rE2vpx/mjra076A==
  template:
    metadata:
      name: mongodb-credentials
      namespace: observatory-dev
