---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: release-proxy-secrets
  namespace: observatory-dev
spec:
  encryptedData:
    s3_access_key: AgAVE/wNVr9sQlZK7D2paM0XCl8bk8UtDUjflc4e2AcDHKP++BefS0AXoPNyjsNR5NmqrpKRJpUQLEjQbQ/ZlaWCql5ANNgg/zWUUQbveco7jJIS2zHi3AYKy8Iush4PZQJOCZhvrE5ur8w+jMJZJfQWAv+R6ZzzfLv8aG7jp172JJmuQmj0mhETEFa2i0vQ1KoJa6KO48KWuV4zDSTYJpo4p6VD7RNlTcNwDS8yifi/L+N29hqzPsX6gAISy3EZdGJBv2QO30te3HOgnda2Q19N/KJfWhMoclUCjzPAKwrC0/CmQ0uoGYbHZA63ZvhnaWpLRIWy4l74pMx6r7yy3t+PhiYLTKvqLMxEHCoj76zd923X3VcnxRGEAKub2fZSdmCK1KTXKOIfTYjKwIC4fQ58sMIqkIeQZuwg32b7l8L+CZZtADmohEYkllEythXB+ohmp80q7qpvRNWUd3b4Mr2EoOAwLnSHCbaCCXLz4kQqLUZCF9CLmOVKYOZmlSGfyMPCh6Nr7gNNvCJ8TaX4IU5dA8MaPf5ooNAvCz+JwMY36jrlRcyvwursev8OQP76t2ObL0YjD1uzIVqzve5NtDch88HOZ+M9F2tnUWK3Cx6omBF8H5FPEk0eSALc9sf5bSoneCDL3Q84IulBUz+ZUGI2fpisJGsPugvWftgH8+j9BlhZRTA1dp0t2JlkLYAsHYxSFGMXI6BvArq9W2Vb0WOGeGx+ag==
    s3_secret_key: AgAG1txCjGUv7KGCmYJwn6hqlMkNUGmKLoCTbd04xXqEvN17MZt0sikLDF2AaoYDGz2MLgfyRXDwCeITE9eqN7qZYD8i3o6In4zT0E0nDrkSCXMS228zI13qlNWLh3ZHQk0mAX4lxaxPgSvkOk41algprKuKa8PSEDGkoDDWpNnZW2XM+YJpfOE43xbLofQjmZkrfhYcyAcfbQ2rcYj8ZNBPQpG+qhUTutyJpsuKA8fSdE6uxy9eS2P3P/yLlnOAWOABIhqVXnNXxNeDecGWR9VkICVFwZCecKyDALBUd96xzLKUlhFGJzJxxovDY6xRPnRd2fwG/QdsU8EyMoo3/L8SlReUZ/Na//wgyMrdYuSzzeTZZL1FQ7ppCVUkXPUyD/A8/eBci5Icru/la+jeBBwqNL4IGjr7Y1m5TGmEwucSvck1WLviirfjeQNEtWHtcNCroEyeCsf/ht7Pys5U1+ZmdWpi+Jpe17DhQiMTYyYwfCVZ3d8sXK6+b8HTmellDK2ZVDq+MXNFqmeVHFHnVvn7g/yB4xgxZwZaIi4QgmyFiQFGIWexFpUhBFtlAtM6iTyrrMfRIeC2q13sfz7qCj3rXGAQbdANT3AyNLoINqPy70SZu8bplg/gBIOC3tEYC9QFHlxgC3i4dcs/l6VvYnue1JK9L35fJ1n7sviZBEg1qfUHuhbPs4mLsOtK/mrgwSGXkucaCaSJsz7G1aI8dvhEueDYN5Tag5bboosZJ+YqVSXo3gO7bJOg
  template:
    metadata:
      name: release-proxy-secrets
      namespace: observatory-dev
