apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observatory-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observatory
  source:
    repoURL: git@github.com:ObservatoryServices/ObservatoryServices.git
    targetRevision: release
    path: infra/k8s/overlays/release
  destination:
    server: https://kubernetes.default.svc
    namespace: observatory-release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
