---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: observatory-prod
spec:
  encryptedData:
    mongodb_uri: AgAih2hoFzsgb0KHnBuzfFmE/rZg3cdCXivR3H7kY/8j69qjnrCyHKtIrtquTScDxIc+V0mLHXDpiCJVCiqqjqxQgebFHIfSN/LYRALygFB5cxEzfJ8T9HUfMr8yYS4O42j4Q1QVa4f4YeeYCgNR/wXhnMZO6KQJevzEkm9534VxS/MUEdUR/5ufPYMtsRKN2hjrG3HL5ngD6G681KoQEswFTD9j5nZttHljW3nKcrpeo3E6Anb7Co5vpKFIYJLDMrNtgG00SWL/yqkEB0twfZetF9iS2LI2Jvuei8O5k+0wXiMm3WTIwcD3a1Z9hzWFF2f0cTiSwb0UDbLFAu7X6OraKRkoqBoAFZLgnH0WsM98Lx8cBZRo/8AAG3Vg65ylvpJrUvK5oPGXC8MkHs0V69Ivb4vOXCVnJ/ndH9SvEg8rrODpwtgA2W7n9cQ2kezRYbsm2QOZCzGjEMnPCnsw6yptV9kT4kmLyjXCWWVezLtxSgzT3Bkcy71HGcia0OWhsnnBPXIQF7KbcSMHK0+Ubjj0bfMXsUtMbMP0BxFZUxiI3+WME4j9PnwVEOWQHfDSI/V7sDZfP4qG6w/pIPDW+P+xVWUL5850VekTVmDV+HON9uRny/+rqnMvqtnM8UMB6tcNE6zJNDpqNgs9JeSKm2XVRnYrFtRWVpFBJdTNP00tUOKgwiTbrIt6O0wKkfcZWHwiYc30e/5pUN3MeVhJP3ZkkrcQaw7KJMfh8gxaDTw9QUkKNHucvQa53cwvcr3j+cpCLpCarnE6X7MFXanfpIrPuyGETN8W33djTW//P6E5qIW6wvJGS6SBN9osmajuwIAj
  template:
    metadata:
      name: api-secrets
      namespace: observatory-prod
