apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observatory-prod

resources:
- ../../base
- mongodb-credentials.sealed.yaml
- api-secrets.sealed.yaml

configMapGenerator:
- literals:
  - environment=prod
  - mongodb_db=observatory
  - s3_endpoint=<S3_ENDPOINT>
  - s3_bucket=observatory-prod
  name: app-config

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: observatory.services
  target:
    kind: Ingress
    name: observatory

images:
- name: ghcr.io/observatoryservices/observatory-services-api
  newName: ghcr.io/observatoryservices/observatory-services-api
  newTag: main-db37f85
- name: ghcr.io/observatoryservices/observatory-services-frontend
  newName: ghcr.io/observatoryservices/observatory-services-frontend
  newTag: main-db37f85
- name: ghcr.io/observatoryservices/observatory-services-release-proxy
  newName: ghcr.io/observatoryservices/observatory-services-release-proxy
  newTag: main-db37f85
