---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: observatory-prod
spec:
  encryptedData:
    password: AgAbWosEiDJQ4W9qxfxS4d6pdhapHvVAE9YRwbPN5aoPIu6qViu/NHK3fafguD0FTbpcTBmbXJogUdAQV7Io9ghAeyN18nIhwEvPdRV2gtY7/0rru+tJ2PnLTn63xPf1SWQIi8sUDBaKJ7JhTpDYzqmqetI5or3Asipk6P2UM/7BcwKd4/ybVy0EQB1oWuq+Kwb332qfzSRA3AJjuazSHnUOPybVWNIKFQN5Af+m9dwUaHG/0d+4jcY58R9dTIQXIyUJsWSMHCrS0wowt6dMwE1yzeMa3pUHKyupphjD25cFi7GqbTUKtGNMePJ6MKtU8uAlVW+bgzHMLiRdpB+jZpxrPV+QhQZeFid/g6cx30yMatVMJtCeM46fGgGOf4kMiARKJq75jiHg5xZnqNCJo3LT3nj7rH6wxU+Z8GUe88c89H6jrHbfS/Dx8bV5Ranjt1tv0jUyLKzjW7IzYy4b3KNuSZTLNG7Y5ef3KBPS0I90LjLaPKv0QhjJDcfI7n8G8vxgoDBYLk76TQMQMfmSU7McuUEjUzFhDfnAt8SEmKEVhSHJyuMP7LBwWrDFlz2/EJAzM1obSY2+67Ruxq/nTxZwWIVMECcE+Pi/8REkOR+sWMHbq9W8G/9KzutmX0/CbLChHa3A1YLQ+v6MnXXzXNHx2orxGx4xHLieYqU7tXvZM/JhDhSb0R/I2LI85C1F0b/tff5z6S1QylFwuWcceycqfUxxgzHUoLAyXuKhxoR+DA==
    username: AgCzpYS223gt4b5cL8+yUwJHyeDi8wDLO6S0TwMnzOm11Xz2tULvsBoE0+bskIVz8E3XJ4saJtyutVXs+qOy39G0FDawWZRsUoK/Pf8NrT2XRjCVtfv98wSoJaXR12PuIKxVWpRLtmJKne1kOQguTVrQi5MNchp+h8yfylt6K2cFJd1C+hRXQdGvmGQwUXd2ezzBOJbjW1R3tLQWy5chjVCrDhnYRzCFIqN6iGrtbTcz19cfyJvf2wujBPrNqUtZWc/5vG4PcIWAlUl/TT3MCey+c5ukQrU+pBgvUhnMNM2HVqpJP/czmVoUwY08QWLFblUhtlvCshEb+jkhGlwI1MwIqfD/xJyBzKEr/Rf4KdqnRYQSPBnCraj6wHRz1ix/iBhtzBP+e2r4+UToAKFYz5AfFeND5U99yZy3DmCrcTX9bsEALW0TxpEdsvO20re0EqVGjNfxTFL0M1MPmLkpBBI/OKF4QzB8bwk40NkSofhSRzn2PbLBtcjrzGzk0x8BVOkG6fEOzP8yfGpF+UzH6XySObrlIrbdvA+LQGhQkzfDVmePwpVAjYQMQTg4Huq9Tii98mV1VAbF/3Mo48+m9ssYBAxHywVrBlYZDVYgetGHmglds3fmPNBNd1awMxk/yjiloec1XTXTsYg2OH1+bSzJFrV9HSqotm8gqwgfq35Ppw+W7fBkPA4Hp5XlyRvjkDl2Ak+K0E8Ie0+T6Q==
  template:
    metadata:
      name: mongodb-credentials
      namespace: observatory-prod
