---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: release-proxy-secrets
  namespace: observatory-prod
spec:
  encryptedData:
    s3_access_key: AgBtS0HKR1xnA629aUvyxpKh5QDCbLxGvXSZSG4tDvqvQi3SuExgYhwTtBnLk+b+lZ0e2KyQYQmtNYF14E7iObw3tHf+Zz9RvcYTrYpnty7/RirEQY2lnGZstKCGIf9pGAkNs2DrwO8GBkZljZYcS1yMm7S3O2+012shnotIdNUpeFYRpr4FcA3m6am6cWIF4O/hM/g11Tn342CZNE2O30JQfVazdeHH5xWsdXUACJAcmTTafwmat8m2ixmyU3J3oOozYyU2NrIhUIDkP730swSxj6TpXRZOzsjFnBIuHgu6GZGO2cap2IosO72Yp/grmN1sObi9UCBX7dAPJjwQN+jXFn5FkPJkNlD/Wns1TKe1I0Yb+5l8wa9HtXbDTiReidJniyxBXbaiomBv/b/hcN/tLjPJQ+yIFZ6xcn1Tj66j/DW1ldj1pCId2MHr9AGwqarlejwbL3lAdabAxI77wG+tSGgGKS4Z/jL3a5J5OaLe4Ckc/lUE1I1uhVBeVYoPuoqqiLgRsv9AkYW+MP/j0SG+9YyrUOSjGDiS8auj1A7hKPzlURgYttmFv4aw3OP6HMcUPRB5qsPJEuPAtQFmh1cKCj2y5HgFQv2D/samKfaRm3+fpFFBj6CdEGtkAAgbuJsnSdt8TAQRPG65spxQGZ+5Lnyx4EZaJ6mggkN2BuYK7TDiMBMTf0/D3+xPdXwPVUI56dyb1aD7NtJ/yvsRLRRj0nDmew==
    s3_secret_key: AgCcnoJ3qPf8eIAUwaIjQ92shdg9/qOBmR6yT+v5AwQX1lGUTlDypyLmdFLzhklm7aCPG+qYjbIsIGyRDdRb3FoK+O2CA7npSdVieyjglesSB5F/PjmJ8ggexHoYgh6kh9Pz2N5VcTKOK+9ENwoQVKnKsWFnb9qf0+yOUwTtKm+K9MaigTHFSPGisUCcKDwyM1eWrnoGRRhKVvvx0hL9lbXWMp84ZMJpO/YKvThAL8yP4nQ2TNf70vIrPcCFmsd4e0aV9yO+TznJn/Se5cNZPg/EkcoCo8s5vBkfuIVdhOKpHgOckYbv5DJp+g7FmRR4D3yfRcjYL2Qu7+ZhowTpenJCNIO2jwGIH8aTSoSHkHsEe4PBRRnMGrQZ8QbxRfZkWKY5l4XTsMURidjDiuZ16iRmH3yYFG5hjW9zpL3UBHNeT1z9Aij1BFbd+CSWex+BlP3hNNMCgq1LgEzX09H/p3KVi85KXFWIUi45bs1/6QacCYS3/Z5VGVMEvg+0Q/YzvrCF3g1fZv8D9JE77BaLmCM2kmcMWmBrMjRycug9vL/AE2hViNrnkdyt9tfViWOLHDu6Khe2H6We2XKssMPkD5e+kxnrsTnUONddElFt/B41H9NYRRhG13FgP6QHdr7ErJ3q3eTg96qfzVkhKNeFzVBkIICuNSUcNgvclHrgENWKRIHuWff5GI6Zji94i1OYBgR7zce+qQCnjNFsiHXD8UwDW0hBzkI7c2lwXsBaHwHUTH3DlTM4Zfwq
  template:
    metadata:
      name: release-proxy-secrets
      namespace: observatory-prod
